steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ingestion-agent \
          --source . \
          --region us-west1 \
          --service-account amie-agent-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com \
          --set-env-vars BUCKET_NAME=amie-manuscripts \
          --allow-unauthenticated
timeout: 900s
