name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/ingestion-agent/**"
      - "frontend/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aime-hello-world

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ingestion-agent \
            --source backend/ingestion-agent \
            --region us-west1 \
            --allow-unauthenticated \
            --build-service-account=cloudbuild@aime-hello-world.iam.gserviceaccount.com \
            --build-service-account=projects/aime-hello-world/serviceAccounts/cloudbuild@aime-hello-world.iam.gserviceaccount.com \
            --set-env-vars BUCKET_NAME=amie-manuscripts,GCP_PROJECT_ID=aime-hello-world,GCP_REGION=us-west1

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build with env
        run: npm run build
        env:
          REACT_APP_INGESTION_URL: ${{ secrets.REACT_APP_INGESTION_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIME_HELLO_WORLD }}
          channelId: live
          projectId: aime-hello-world
          entryPoint: frontend
