name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
      - name: Print env var for debugging
        run: echo "REACT_APP_INGESTION_URL=$REACT_APP_INGESTION_URL"
        env:
          REACT_APP_INGESTION_URL: ${{ secrets.REACT_APP_INGESTION_URL }}

      - name: Build React app with env var
        run: npm run build
        env:
          REACT_APP_INGESTION_URL: ${{ secrets.REACT_APP_INGESTION_URL }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIME_HELLO_WORLD }}
          channelId: live
          projectId: aime-hello-world
          entryPoint: frontend
